@startuml
'https://plantuml.com/sequence-diagram

autonumber


Frontend -> REST_API: POST /api/routes
REST_API -> TripService: CreateSavedRoute()
TripService -> RouteRepository: saveRoute()
database MySQL
RouteRepository -> MySQL
RouteRepository -> TripService: routeId
TripService -> REST_API: RouteDTO
REST_API -> Frontend: 201 Successfully created favorite route, /api/routes/{routeId}


@enduml