@startuml
'https://plantuml.com/component-diagram

package "Frontend" {
    component Frontend_UI
}

package "Backend" {

    component REST_API

    package "Controllers" {
        component TripController
        component SightsController
    }

    package "Server Logic" {
        component TripService
        component SightsService
    }

    component EnturClient
    database MySQL
}

' --- Relasjoner
Frontend_UI --> REST_API

REST_API --> TripController
REST_API --> SightsController

TripController --> TripService
TripService --> EnturClient
TripService --> MySQL

SightsController --> SightsService
SightsService --> MySQL

@enduml
