@startuml
'https://plantuml.com/component-diagram

package "Frontend" {
    [Frontend UI] as Frontend_UI
}

package "Backend" {

    [REST API\n(Javalin Endpoints)] as REST_API

    package "Server Logic" {
        [TripController]
        [TripService]
        [SightsController]
        [SQLdbConnect]
        [DTOs]
    }

    package "Persistence" {
        [TripRepository]
        [SQLConnector]
        [SQLProcedures]
        database MySQL
    }

    [EnturClient]
}

' Relasjoner – Trip-flow

Frontend_UI --> REST_API : POST /api/trip (JSON)
REST_API --> TripController
TripController --> TripService
TripService --> EnturClient : GraphQL queries
TripService --> TripRepository
TripRepository --> MySQL

' Relasjoner – Sights-flow
Frontend_UI --> REST_API : POST /api/sights (JSON)
REST_API --> SightsController : getSight(city)
SightsController --> SQLdbConnect : getArrayListOfCity()
SQLdbConnect --> SQLConnector : getAllPois(SQLProcedure)
SQLConnector --> SQLProcedures : predefined SQL views
SQLConnector --> MySQL : SELECT * FROM viewCityPois

SQLConnector --> SQLdbConnect : List<PoiDTO>
SQLdbConnect --> SightsController : [[Food],[Culture]]
SightsController --> REST_API : JSON response

@enduml
