@startuml
'https://plantuml.com/component-diagram


   package "Frontend" {
       [Frontend UI] as Frontend_UI
   }

   package "Backend" {

       [REST API\n(TripController)] as REST_API

       package "Server Logic" {
           [TripService]
           [TouristSightService]
           [DTOs]
       }

       package "Persistence" {
           [TripRepository]
           [TouristSightRepository]
           database MySQL
       }

       [EnturClient]


   ' --- Relasjoner mellom komponentene ---
   Frontend_UI --> REST_API : HTTP requests (JSON)
   REST_API --> TripService
   TripService --> EnturClient : GraphQL queries
   TripService --> TripRepository
   TouristSightService --> TouristSightRepository
   TripRepository --> MySQL
   TouristSightRepository --> MySQL
@enduml
