@startuml
'https://plantuml.com/class-diagram

class TouristSight {
    - name: String
    - longitude: double
    - latitude: double
}

class Turist {
    - person: Person
    - touristSight: TouristSight
}


@enduml