@startuml
'https://plantuml.com/sequence-diagram

autonumber



Frontend  -> Controller
Controller -> TripService: getTripFormData(from, to, numTripPatterns, dateTime)
TripService -> EnturClient: getTrip(TripRequest)
EnturClient --> TripService: 200 OK\n+ Entur JSON response
TripService -> TripDTO: map & filter Entur data
TripDTO --> TripService: TripResponse objekt
TripService --> Controller: TripResponse
Controller --> Frontend: 200 OK\n+ TripResponse (JSON)


@enduml